services:
    postgres:
        environment:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        image: postgres:13.1
        restart: always
        ports:
            - "5432:5432"
        volumes:
          - fastapi_db_data:/home/postgresql
          - fastapi_db_data:/var/log/postgresql
        networks:
          - net

networks:
  net:

volumes:
    fastapi_db_data:
        external: true